### PR TITLE
[BUGFIX] Fix embedding of images

### PR DESCRIPTION
**Pull request by tobenschmidt**
Remove usage of method mime_content_type which does not work with basename($media['absRef'] as argument. Instead use API method embed to embed images with Content-ID standard.

### CODE REVIEW

**Comment by kartolo** [comment]
Thank you for the patch.

**Comment by chrcan** [comment]
Hello,
I have made all the changes and now I get the error message:
Oops, an error occurred!
The body of "Symfony \ Component \ Mime \ Part \ TextPart" must be a string or a resource (got "bool").

**Comment by kartolo** [comment]
@chrcan: could you please document the steps? thanks

**Comment by chrcan** [comment]
1. i grap my Newsletter from the internal pages
2. Detailed Information push the button next
3. Categories next
4. Test Mail ignore next
5. Mass Send pic the Send mail - recipient list admin push the button Send to all subscribers in recipient list
6. Mass Send Mail scheduled for distribution The mail was scheduled for distribution at 26-10-20 11:04
7. push the buttom Mailer Engine Status
8. push the Invoke Mailer Engine 
9. Error = Oops, an error occurred!
The body of "Symfony\Component\Mime\Part\TextPart" must be a string or a resource (got "bool").

i work with TYPO 10.4.9

**Pull request merged**
