### PR TITLE
Update for TYPO3 8 LTS

### PR DESCRIPTION
**Pull request by webian**
Not tested with TYPO3 versions < 8 LTS

Ref: #53

### CODE REVIEW

**Comment by patkar** [comment]
Please update the composer.json too. See our fork: https://github.com/pixelart/direct_mail/blob/compat/typo3-v8/composer.json#L24-L27

**Comment by webian** [comment]
@patkar ok but what is this for?
https://github.com/pixelart/direct_mail/blob/compat/typo3-v8/composer.json#L32

**Comment by patkar** [comment]
This is for autoloading the included Fetch library. Not the best way to autoload that in the extension, instead of requiring that with composer too. But it's already there, so not in the scope of the PR to fix that ;)

**Comment by runepiper** [comment]
👍

**Comment by mkoitka** [comment]
Thanks, this already works great! Though there is an issue if a planned sending date is set, because TYPO3 now uses ISO dates instead of timestamps for the DateTime picker. As of now Direct Mail can't interpret the incoming date and just uses the current timestamp.

Sadly, I currently don't have a clean solution for this. But the problem can be seen in Classes/Module/Dmail.php Line 1083. We could convert the incoming ISO date to a timestamp, but would also have to deal with the correct timezone offset.

**Comment by kartolo** [comment]
Thanks for the PR, I'll check this.

**Comment by kartolo** [comment]
I merged this PR, this one works also for 7.6 LTS.
There's some things that needs to be changed.
Like:

1. remove debug
2. changed dependency

Thanks

**Pull request merged**
