### PR TITLE
[BUGFIX] don't send empty HTML part

### PR DESCRIPTION
**Pull request by kartolo**
Resolves: #247
Releases: develop

### CODE REVIEW

**Comment by gilas1959** [comment]
hi I can always reproduce this error on two Debian Servers. Hope you can solve.
I tried to send a quickmail via test email: MS Outlook do not consider the body and seems to be not received; another differente WEBAMAIL (Aruba) display correctly the body.
However the problems occurs only just updated direct_mail to the version compatibile with TYPO3 v.10.4; before with v. 9.5 al was OK!

**Comment by gilas1959** [comment]
I have just made some other tests, but the problem persists:

* tried to send the email using only html option, changed the charsetm etc. without success

to be more precise, I have sent a test mail using the TYPO3 function from ENVIRONMENT - in this case the test email starts correcly and the body is shown

My site is configured as client of Outlook server with connection toward the 587 port.

thank you

**Comment by gilas1959** [comment]
hi I tried and added the solution #252 moreover I substituted

        if ($this->theParts['plain']) {

with

   if ($this->theParts['plain']['content']) {

and this solved the problems for QUICKMAIL mode

**Comment by kartolo** [comment]
> hi I tried and added the solution #252 moreover I substituted
> 
> ```
>     if ($this->theParts['plain']) {
> ```
> 
> with
> 
> if ($this->theParts['plain']['content']) {
> 
> and this solved the problems for QUICKMAIL mode

which line?

**Comment by kartolo** [comment]
is it line 930? please check

**Comment by gilas1959** [comment]
thanks, it is the line 930, have a look here (copied and pasted from my Dmail.php)

     if ($this->theParts['plain']['content']) {
            $mailer->text($this->theParts['plain']['content']);
        }

wonderful! Thank you very much!

**Pull request merged**
